### ISSUE TITLE
Sample-user audit follow-ups (search_k PR #731): pre-existing API friction

### ISSUE THREAD

**Issue by nealcaren** [nealcaren/topica#732]
Two independent first-time users (Dr. Priya Anand on `load_dubois`, Dr. Marcus Bell on `load_poliblog`) ran the `sample-user` acceptance gate on PR #731. All three #730 fixes passed. The items below are **pre-existing** friction they hit along the way, not introduced by #731 — filed for follow-up.

### Tier 1 — analytical trap (already partially mitigated)
- [ ] **`estimate_effect` auto-adds an intercept, so `coef[0]` is the intercept, not the first covariate.** A user mapping `feature_names -> coef` by index reports the intercept as the covariate effect. The docstring already warns against reading `coef[0]`, and `e.effect_of(name)` reads by name — but the raw `.coef`/`.se`/`.z` arrays still invite off-by-one. Consider returning a name→estimate mapping (or a labeled frame) so index matching is never required. (Both users flagged; Claude noted the docs caught her in time.)

### Tier 3 — return-shape / signature inconsistency
- [ ] **`bootstrap_stability` breaks the library-wide `num_topics=` convention.** `bootstrap_stability(corpus, num_topics=15, ...)` raises `pass k (number of topics) or a fitted reference model`; the accepted kwarg is `k=`. Every constructor is `LDA(num_topics=...)`. Accept `num_topics=` as an alias. It also returns a plain `dict` rather than a `.to_frame()`-capable result like `search_k`; consider a small result class.
- [ ] **`coherence` has no `metric=` kwarg.** `coherence(model, corpus, metric="c_v")` raises `unexpected keyword argument 'metric'`. Document whether it returns a single default metric or a bundle, and expose/standardize metric selection.
- [ ] **`topic_table` vs `label_topics` return-shape mismatch.** `topic_table` rows carry bare word strings (`row["frex"] = ['jail', ...]`); `label_topics` returns `(word, score)` tuples. Reusing the `label_topics` unpack idiom on a `topic_table` row raises `ValueError: too many values to unpack`. The `topic_table` docstring already predicts the error; mirror the note on `label_topics`, or expose both `.words`/`.pairs`.

### Tier 4 — discoverability / docs
- [ ] **`best_k()` default lands on the grid edge on real corpora.** With a held-out set, the default `heldout_loglik` criterion is billed as "the principled, non-monotone criterion" but is near-monotone on Du Bois (K=10..30), so `best_k()` returns K=30 (over-fragmented). The grid-edge warning fires and names `rule='elbow'`/`frontier`, so it is a near-miss, not a live trap. Soften the "non-monotone" framing, and have the grid-edge warning cite the elbow/frontier picks it already computes.
- [ ] **`load_poliblog` text-column ambiguity.** `from_dataframe(text_col="blog")` crashes with "corpus has no words after frequency filtering" because `blog` is a covariate (blog name); the text column is `text`. A doc-string note on the dataset columns and/or a clearer empty-corpus error ("text column 'blog' produced empty documents; check the column") would save the guess.
- [ ] **Quickstart `ENGLISH_STOPWORDS` under-cleans some corpora.** It is only 115 words; on the Du Bois quickstart path the magazine's own name ("crisis") surfaced in a topic. The Du Bois worked example fixes this with a larger stoplist + corpus-specific extras, but that lesson lives in the example, not the quickstart. Add a one-line quickstart tip.

### What delighted (keep and advertise)
- The `best_k`/`search_k` grid-edge and monotone-metric warnings — both users called them best-in-class "honest diagnostics."
- Docstrings that predict the exact error you are about to hit (`Corpus.__doc__` names the `TypeError`; `topic_table.__doc__` names the unpacking `ValueError`).
- `one_hot` returning `(X, names)` together; the covariate path steering to a correct, uncertainty-bearing result without forcing STM.
- Speed + determinism: identical-seed fits are bit-identical.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
